### PR TITLE
Add new location images

### PR DESCRIPTION
**Pull request by caseycesari**
These images were created by TNC for the new regions added to the [production site](http://maps.coastalresilience.org/network/). I downloaded and added them there.

### CODE REVIEW

**Comment by caseycesari** [comment]
Forgot to add the new images for the subregions. I'll squash these commits down before merging.

**Review by kellyi — CHANGES_REQUESTED** [review]
This is mostly working well! Some of the images here aren't being found because they're in `./` rather than `./src/assets/images/locations/`. For example: `java-indonesia.svg`. Moving them to that dir fixes the missing file error.

**Comment by caseycesari** [comment]
Thanks. Good catch. Pushed a fixup (I'll get rid of the merge commit).

**Review by kellyi — APPROVED** [review]

**Comment by caseycesari** [comment]
Thanks!

**Pull request merged**
